// <auto-generated />
using System;
using LoanAmortizationCalculator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAmortizationCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(LoanAmortizationContext))]
    [Migration("20240602181536_DownPayment")]
    partial class DownPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.GracePeriodUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GracePeriodUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Days"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weeks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Months"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Years"
                        });
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GracePeriodUnitId")
                        .HasColumnType("int");

                    b.Property<int>("GracePeriodValue")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<int>("LoanDurationUnitId")
                        .HasColumnType("int");

                    b.Property<int>("LoanDurationValue")
                        .HasColumnType("int");

                    b.Property<int>("PaymentFrequencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GracePeriodUnitId");

                    b.HasIndex("LoanDurationUnitId");

                    b.HasIndex("PaymentFrequencyId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.LoanDurationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoanDurationUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Days"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weeks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Months"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Years"
                        });
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.LoanPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeginningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EndingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GraceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.PaymentFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentFrequencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quarterly"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SemiAnnually"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Annually"
                        });
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.Loan", b =>
                {
                    b.HasOne("LoanAmortizationCalculator.Domain.Entities.GracePeriodUnit", "GracePeriodUnit")
                        .WithMany()
                        .HasForeignKey("GracePeriodUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAmortizationCalculator.Domain.Entities.LoanDurationUnit", "LoanDurationUnit")
                        .WithMany()
                        .HasForeignKey("LoanDurationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAmortizationCalculator.Domain.Entities.PaymentFrequency", "PaymentFrequency")
                        .WithMany()
                        .HasForeignKey("PaymentFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GracePeriodUnit");

                    b.Navigation("LoanDurationUnit");

                    b.Navigation("PaymentFrequency");
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.LoanPayment", b =>
                {
                    b.HasOne("LoanAmortizationCalculator.Domain.Entities.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAmortizationCalculator.Domain.Entities.Loan", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
